In [1]:
import tensorflow as tf
print("TensorFlow version:", tf.__version__)

2021-10-25 02:34:56.134978: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2021-10-25 02:34:56.135010: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.


TensorFlow version: 2.6.0


In [2]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

11501568/11490434 [==============================] - 1s 0us/step


In [3]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

2021-10-25 02:36:27.781315: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2021-10-25 02:36:27.781350: W tensorflow/stream_executor/cuda/cuda_driver.cc:269] failed call to cuInit: UNKNOWN ERROR (303)
2021-10-25 02:36:27.781368: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (ubuntu): /proc/driver/nvidia/version does not exist
2021-10-25 02:36:27.781830: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [4]:
predictions = model(x_train[:1]).numpy()
predictions

array([[ 0.50855833, -0.14878666,  0.1908882 , -0.1792977 ,  0.11047373,
         0.1540425 ,  0.8775883 , -0.2643423 ,  0.9653941 , -1.2676163 ]],
      dtype=float32)

In [5]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [6]:
loss_fn(y_train[:1], predictions).numpy()

2.4058404

In [7]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [8]:
model.fit(x_train, y_train, epochs=5)

2021-10-25 02:40:10.252543: W tensorflow/core/framework/cpu_allocator_impl.cc:80] Allocation of 188160000 exceeds 10% of free system memory.
2021-10-25 02:40:10.464626: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:185] None of the MLIR Optimization Passes are enabled (registered 2)


Epoch 1/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.2958 - accuracy: 0.9152
Epoch 2/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.1419 - accuracy: 0.9583
Epoch 3/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.1089 - accuracy: 0.9676
Epoch 4/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0890 - accuracy: 0.9719
Epoch 5/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0760 - accuracy: 0.9761


In [9]:
model.evaluate(x_test,  y_test, verbose=2)

2021-10-25 02:41:04.521211: W tensorflow/core/framework/cpu_allocator_impl.cc:80] Allocation of 31360000 exceeds 10% of free system memory.


313/313 - 0s - loss: 0.0757 - accuracy: 0.9779


[0.0757073163986206, 0.9779000282287598]

In [10]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

In [11]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[9.83467174e-09, 8.95782837e-10, 4.16868261e-06, 9.79735923e-05,
        8.05929712e-10, 5.12566260e-07, 8.61462458e-14, 9.99892592e-01,
        1.49655747e-07, 4.60194042e-06],
       [7.69491351e-08, 6.38867205e-04, 9.99345958e-01, 1.42637364e-05,
        1.25829997e-14, 5.35692834e-07, 1.64401300e-07, 2.42141512e-14,
        9.31501916e-08, 2.92853984e-13],
       [8.50770505e-07, 9.99078989e-01, 2.50561807e-05, 1.58080479e-06,
        1.68073238e-04, 4.63981405e-06, 1.40363758e-04, 4.94471460e-04,
        8.44823880e-05, 1.46746720e-06],
       [9.99876618e-01, 4.97933986e-12, 4.15825707e-06, 3.18383115e-08,
        9.10432529e-09, 1.19200209e-07, 1.15560964e-04, 2.63044990e-06,
        7.14355908e-09, 9.12136784e-07],
       [1.89689945e-06, 4.72529871e-12, 2.55492097e-07, 2.45122617e-10,
        9.98746037e-01, 1.81088371e-08, 9.08029136e-08, 3.68512789e-04,
        3.18121863e-07, 8.82906606e-04]], dtype=float32)>